theme: jekyll-theme-minimal
title: Data Story for Surviving4ADA
description: This is the data story for team Surviving4ADA.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
